---
include:
 # - board: eyelash_sofle_left
#    shield: nice_view
  - board: eyelash_sofle_right
    shield: nice_view_gem
  - board: eyelash_sofle_left
    shield: nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_left
  - board: eyelash_sofle_left
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: sofle_dongle_pro_micro
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Xiao_Dongle\" -DCONFIG_ZMK_STUDIO=y
    artifact-name: xiao_corne_dongle_xiao
    snippet: studio-rpc-usb-uart
